# Generated by Django 6.1 on 2026-08-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='series',
            name='language',
            field=models.JSONField(blank=True, default=list, max_length=50),
        ),
    ]
